version: '3'
services:
  webserver:
    image: node:14.4.0-buster
    tty: true
    volumes:
      - ./:/app
      - volume-node-modules:/app/node_modules
    working_dir: "/app"
    ports:
      - "8080:8080"

volumes: 
  volume-node-modules: